version: "3.8"
services:

  db:
    image: "postgres:13"
    container_name: "polardb-order-postgresql"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db

  mq:
    image: "rabbitmq:3-management"
    container_name: "polarmq-broker-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
